---
- name: Deploy ClickHouse Infrastructure
  hosts: clickhouse_node
  become: true
  tags:
    - clickhouse
  roles:
    - clickhouse

- name: Deploy Vector Infrastructure
  hosts: vector_node
  become: true
  tags:
    - vector
  roles:
    - vector-role

- name: Deploy Lighthouse Infrastructure
  hosts: lighthouse_node
  become: true
  tags:
    - lighthouse
  roles:
    - lighthouse-role